# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"

database:
  nucleotide: "/cluster/projects/mcgahalab/ref/metagenomics/biobakery_workflows_databases/humann/chocophlan/"
  protein: "/cluster/projects/mcgahalab/ref/metagenomics/biobakery_workflows_databases/humann/uniref/"
  kneaddata: "/cluster/projects/mcgahalab/ref/metagenomics/biobakery_workflows_databases/kneaddata_db/hg37"
  bowtie2db: "/cluster/projects/mcgahalab/ref/metagenomics/biobakery_workflows_databases/metaphlan/metaphlan_databases"
  metaphlan_pkl: "/cluster/projects/mcgahalab/ref/metagenomics/biobakery_workflows_databases/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.pkl"

tools:
  trimmomatic: "/cluster/projects/mcgahalab/bin/trimmomatic-0.39-2"

resources:
  metaphlan_nproc: 4
  humann_nproc: 4
  strainphlan_nproc: 4

env:
  conda_shell: "~/miniconda3/etc/profile.d/conda.sh"
  biobakery3_core: "/cluster/projects/mcgahalab/envs/biobakery3_core"
  r41: "/cluster/projects/mcgahalab/envs/r41"
